# Generated by Django 2.2.6 on 2019-12-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
