# Generated by Django 2.2.6 on 2019-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191205_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='poojano',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
