# Generated by Django 2.2.6 on 2019-11-26 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191017_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='god',
            field=models.CharField(choices=[('1', 'Krishna'), ('2', 'Ganapathi'), ('1', 'Devi'), ('1', 'Ayyappa')], default=django.utils.timezone.now, max_length=2, verbose_name='God'),
            preserve_default=False,
        ),
    ]
