# Generated by Django 2.2.6 on 2019-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191126_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='god',
            field=models.CharField(choices=[('Krishna', 'Krishna'), ('Ganapathi', 'Ganapathi'), ('Devi', 'Devi'), ('Ayyappa', 'Ayyappa')], max_length=2, verbose_name='God'),
        ),
    ]
