# Generated by Django 2.2.6 on 2019-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191202_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pooja', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
